### ISSUE TITLE
withTRPC and VERCEL_URL

### ISSUE THREAD

**Issue by tianhuil** [KATT/envsafe#114]
The documentation for [next.js SSR for trpc](https://trpc.io/docs/ssr) requires us to set the following in `_app.tsx`:

```tsx
const url = process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}/api/trpc`
      : 'http://localhost:3000/api/trpc';
```

I tried using `envsafe` with this with `devDefault`.  This failed when performing a `yarn build` on my local machine (and was the only variable to do so).  It works fine in `yarn dev` (presumably because `VERCEL_URL` is set by nextjs) but doesn't work when building.  What's the recommended solution for `yarn build`?

**Comment by KATT** [comment]
You can't use it in `_app.tsx` because that file is loaded on both the server and the client and envsafe will throw when it hits a bad env var.

I don't use this package much myself anymore as I have zod everywhere which is more powerful. 

https://github.com/trpc/examples-next-prisma-starter/blob/main/src/server/env.js

**Comment by KATT** [comment]
Feel free to use the help channel on discord if you need help

**Comment by KATT** [comment]
https://trpc.io/discord
